// Auto-generated by scripts/sync_sample_assets.py — do not edit.
import type { GalleryItem } from '@/lib/api';

export const OFFICIAL_SAMPLE_AUTHOR = "官方示例 · R40 实测";

export const OFFICIAL_SAMPLES: GalleryItem[] = [
  {
    "id": "sample-xunyu_yingxiandi",
    "kind": "official",
    "title": "荀彧劝曹操迎献帝",
    "subtitle": "汉末 196 年 · 谋士定鼎大局的关键一夜",
    "genre": "ancient",
    "style": "ancient_3d_guoman",
    "video_url": "/samples/xunyu_yingxiandi.mp4",
    "cover_url": "/samples/xunyu_yingxiandi.jpg",
    "quality_score": 96,
    "episodes": 1,
    "author_label": "官方示例 · HappyHorse 真实生成"
  },
  {
    "id": "sample-nie01",
    "kind": "official",
    "title": "兰若惊鸿",
    "subtitle": "夜投兰若寺，初见小倩魂",
    "genre": "ancient",
    "style": "ancient_3d_guoman",
    "video_url": "/samples/nie01_lanruosi.mp4",
    "cover_url": "/samples/nie01_lanruosi.jpg",
    "quality_score": 97,
    "episodes": 1,
    "author_label": "官方示例 · R40 实测"
  },
  {
    "id": "sample-nie02",
    "kind": "official",
    "title": "小倩出场",
    "subtitle": "月白冷青夜，朱砂痣定格",
    "genre": "ancient",
    "style": "ancient_3d_guoman",
    "video_url": "/samples/nie02_appears.mp4",
    "cover_url": "/samples/nie02_appears.jpg",
    "quality_score": 96,
    "episodes": 1,
    "author_label": "官方示例 · R40 实测"
  },
  {
    "id": "sample-nie03",
    "kind": "official",
    "title": "剑指燕赤霞",
    "subtitle": "友人脉象抽搐，剑光出鞘",
    "genre": "ancient",
    "style": "ancient_3d_guoman",
    "video_url": "/samples/nie03_yan_chixia.mp4",
    "cover_url": "/samples/nie03_yan_chixia.jpg",
    "quality_score": 97,
    "episodes": 1,
    "author_label": "官方示例 · R40 实测"
  },
  {
    "id": "sample-xiyou01",
    "kind": "official",
    "title": "石猴出世",
    "subtitle": "花果山 · 西游记开篇",
    "genre": "xuanhuan",
    "style": "ancient_3d_guoman",
    "video_url": "/samples/xiyou01_immortal_stone.mp4",
    "cover_url": "/samples/xiyou01_immortal_stone.jpg",
    "quality_score": 95,
    "episodes": 1,
    "author_label": "官方示例 · R40 实测"
  },
  {
    "id": "sample-real05",
    "kind": "official",
    "title": "回廊月影",
    "subtitle": "系统真实生成 · 聊斋氛围",
    "genre": "ancient",
    "style": "ancient_3d_guoman",
    "video_url": "/samples/real05_moon_corridor.mp4",
    "cover_url": "/samples/real05_moon_corridor.jpg",
    "quality_score": 96,
    "episodes": 1,
    "author_label": "官方示例 · R40 实测"
  },
  {
    "id": "sample-real06",
    "kind": "official",
    "title": "魂影定格",
    "subtitle": "系统真实生成 · 15s 钩子镜",
    "genre": "ancient",
    "style": "ancient_3d_guoman",
    "video_url": "/samples/real06_spirit_hook.mp4",
    "cover_url": "/samples/real06_spirit_hook.jpg",
    "quality_score": 96,
    "episodes": 1,
    "author_label": "官方示例 · R40 实测"
  }
];
