"""Shared helpers for the six V10 data models."""
from __future__ import annotations

import json
import pathlib
import sys
from datetime import datetime, timezone
from typing import Any

_REPO = pathlib.Path(__file__).resolve().parents[2]
DATA_DIR = _REPO / "data" / "data_models"
DOCS_DIR = _REPO / "docs" / "data_models"
DATA_DIR.mkdir(parents=True, exist_ok=True)
DOCS_DIR.mkdir(parents=True, exist_ok=True)


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def write_json(name: str, payload: dict[str, Any]) -> pathlib.Path:
    path = DATA_DIR / f"{name}.json"
    payload.setdefault("generated_at_utc", utc_now_iso())
    payload.setdefault("source", f"tools/data_models/{name}.py")
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False),
                    encoding="utf-8")
    return path


def write_markdown(name: str, body: str) -> pathlib.Path:
    path = DOCS_DIR / f"{name}.md"
    header = (
        f"<!-- AUTO-GENERATED by tools/data_models/{name}.py · "
        f"{utc_now_iso()} -->\n\n"
    )
    path.write_text(header + body, encoding="utf-8")
    return path


def render_table(headers: list[str], rows: list[list[Any]]) -> str:
    """Render a GitHub-flavoured markdown table."""
    sep = "| " + " | ".join(headers) + " |"
    align = "| " + " | ".join("---" for _ in headers) + " |"
    body_lines = []
    for row in rows:
        cells = [_fmt(c) for c in row]
        body_lines.append("| " + " | ".join(cells) + " |")
    return "\n".join([sep, align, *body_lines])


def _fmt(v: Any) -> str:
    if isinstance(v, float):
        if abs(v) >= 100:
            return f"{v:,.1f}"
        if abs(v) >= 1:
            return f"{v:,.2f}"
        return f"{v:.4f}"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)


def parse_cli_out(default_out: str | None = None) -> dict[str, Any]:
    """Tiny argv parser, no argparse import for snappy startup."""
    args = {"out_dir": default_out}
    it = iter(sys.argv[1:])
    for tok in it:
        if tok in ("-o", "--out"):
            args["out_dir"] = next(it, default_out)
        elif tok in ("-h", "--help"):
            print("usage: python -m tools.data_models.<model> [--out DIR]")
            sys.exit(0)
    return args
