#requires -Version 5.1
<#
.SYNOPSIS
    将 Windows 全局存储的 API Key 注入当前 PowerShell 会话.

.DESCRIPTION
    sync_keys_to_windows.ps1 把 Key 写到了:
      1. HKCU\Environment (用户级环境变量) - setx
      2. Credential Manager - cmdkey /generic:XYQ_*

    本脚本反向把它们加载到 $env: 命名空间, 用于:
      a. 在新项目里 dot-source 一次即可有全部 keys
      b. 在 CI / Docker / 临时 shell 不想等 setx 生效时立即取值

    用法:
      . .\scripts\load_global_keys.ps1                       # 加载 setx 注入的
      . .\scripts\load_global_keys.ps1 -FromCredentialManager # 同时读凭据管理器
      . .\scripts\load_global_keys.ps1 -WriteToDotEnv .env    # 顺便落回一份 .env

.PARAMETER FromCredentialManager
    额外从 Windows Credential Manager 读 XYQ_<KEY> 凭据 (vault API, 比 cmdkey /list 更准).

.PARAMETER WriteToDotEnv
    把加载结果落到指定 .env 文件 (新项目快速 bootstrap).

.PARAMETER Quiet
    不打印加载日志.
#>
[CmdletBinding()]
param(
    [switch]$FromCredentialManager,
    [string]$WriteToDotEnv = "",
    [switch]$Quiet
)

# Keys 列表与 sync 脚本保持一致
$KnownKeys = @(
    "VOLC_ACCESS_KEY","VOLC_SECRET_KEY","VOLC_ARK_API_KEY","ARK_API_KEY",
    "DOUBAO_API_KEY","DOUBAO_ENDPOINT_ID","DOUBAO_MODEL","DOUBAO_TTS_APPID",
    "DOUBAO_TTS_TOKEN","DOUBAO_TTS_CLUSTER","ARK_BASE_URL","VOLC_ARK_ENDPOINT",
    "VOLC_ARK_ENDPOINT_ID","VOLC_REGION","TOS_BUCKET","TOS_ENDPOINT",
    "S3_ACCESS_KEY","S3_SECRET_KEY","S3_BUCKET","S3_ENDPOINT","S3_REGION",
    "ALIYUN_ACCESS_KEY_ID","ALIYUN_ACCESS_KEY_SECRET",
    "ALIBABA_CLOUD_ACCESS_KEY_ID","ALIBABA_CLOUD_ACCESS_KEY_SECRET",
    "DASHSCOPE_API_KEY","TONGYI_API_KEY","OSS_REGION","OSS_ENDPOINT",
    "DASHSCOPE_MODEL","TONGYI_MODEL",
    "DEEPSEEK_API_KEY","DEEPSEEK_MODEL","GLM_API_KEY","GLM_MODEL",
    "MOONSHOT_API_KEY","MOONSHOT_MODEL","MISTRAL_API_KEY","MISTRAL_MODEL",
    "GROQ_API_KEY","GROQ_MODEL","XAI_API_KEY","XAI_MODEL",
    "SPARK_API_KEY","SPARK_MODEL",
    "ANTHROPIC_API_KEY","ANTHROPIC_MODEL","ANTHROPIC_BASE_URL","GEMINI_API_KEY",
    "TENCENT_SECRET_ID","TENCENT_SECRET_KEY","TENCENT_REGION"
)

function Get-CredentialManagerSecret {
    param([string]$Target)
    # 使用 Windows Vault API (Windows.Security.Credentials.PasswordVault)
    # 比 cmdkey /list 解析更稳; 但 PasswordVault 只支持 Windows 8+ Store apps
    # 因此走 advapi32 CredRead 的 P/Invoke 兜底
    Add-Type -Namespace Win32 -Name CredMan -ErrorAction SilentlyContinue -MemberDefinition @"
        [DllImport("advapi32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        public static extern bool CredRead(string target, int type, int reservedFlag, out IntPtr CredentialPtr);
        [DllImport("advapi32.dll", SetLastError = true)]
        public static extern void CredFree(IntPtr cred);

        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        public struct CREDENTIAL {
            public int Flags;
            public int Type;
            public IntPtr TargetName;
            public IntPtr Comment;
            public long LastWritten;
            public int CredentialBlobSize;
            public IntPtr CredentialBlob;
            public int Persist;
            public int AttributeCount;
            public IntPtr Attributes;
            public IntPtr TargetAlias;
            public IntPtr UserName;
        }
"@
    $ptr = [IntPtr]::Zero
    if (-not [Win32.CredMan]::CredRead($Target, 1, 0, [ref]$ptr)) { return $null }
    try {
        $cred = [System.Runtime.InteropServices.Marshal]::PtrToStructure($ptr, [type][Win32.CredMan+CREDENTIAL])
        if ($cred.CredentialBlobSize -gt 0) {
            $bytes = New-Object byte[] $cred.CredentialBlobSize
            [System.Runtime.InteropServices.Marshal]::Copy($cred.CredentialBlob, $bytes, 0, $cred.CredentialBlobSize)
            return [System.Text.Encoding]::Unicode.GetString($bytes).TrimEnd([char]0)
        }
        return $null
    } finally {
        if ($ptr -ne [IntPtr]::Zero) { [Win32.CredMan]::CredFree($ptr) }
    }
}

$loaded = @{}
foreach ($k in $KnownKeys) {
    # 1) 优先从用户环境变量读 (setx 写的)
    $val = [Environment]::GetEnvironmentVariable($k, "User")
    if ([string]::IsNullOrEmpty($val) -and $FromCredentialManager) {
        # 2) fallback 到凭据管理器
        try {
            $val = Get-CredentialManagerSecret -Target "XYQ_$k"
        } catch {
            $val = $null
        }
    }
    if (-not [string]::IsNullOrEmpty($val)) {
        Set-Item -Path "env:$k" -Value $val -Force
        $loaded[$k] = $val
    }
}

if (-not $Quiet) {
    Write-Host "load_global_keys: 已注入 $($loaded.Count) / $($KnownKeys.Count) 个 Key 到当前会话" -ForegroundColor Green
    if ($FromCredentialManager) {
        Write-Host "  (含凭据管理器读取)" -ForegroundColor DarkGray
    }
}

if ($WriteToDotEnv) {
    $lines = @("# Generated by load_global_keys.ps1 at $((Get-Date).ToString('o'))")
    foreach ($k in ($loaded.Keys | Sort-Object)) {
        $lines += "$k=$($loaded[$k])"
    }
    $content = ($lines -join "`r`n") + "`r`n"
    [System.IO.File]::WriteAllText($WriteToDotEnv, $content, [System.Text.UTF8Encoding]::new($false))
    if (-not $Quiet) { Write-Host "  并写入 $WriteToDotEnv" -ForegroundColor Cyan }
}
