#!/usr/bin/env python3
"""Copy repo sample/*.mp4 into web/public/samples and emit catalog JSON/TS."""
from __future__ import annotations

import json
import pathlib
import shutil
import subprocess
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
CATALOG = ROOT / "config" / "sample_catalog.yaml"
OUT_DIR = ROOT / "web" / "public" / "samples"
TS_OUT = ROOT / "web" / "lib" / "sample-catalog.ts"


def _poster(src_mp4: pathlib.Path, dest_jpg: pathlib.Path) -> bool:
    try:
        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-ss",
                "1",
                "-i",
                str(src_mp4),
                "-frames:v",
                "1",
                "-q:v",
                "2",
                str(dest_jpg),
            ],
            check=True,
            capture_output=True,
        )
        return dest_jpg.is_file()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False


def main() -> int:
    with CATALOG.open(encoding="utf-8") as f:
        data = yaml.safe_load(f)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    author = data.get("author_label", "官方示例 · R40 实测")
    entries: list[dict] = []

    for s in data.get("samples", []):
        src = ROOT / s["source"]
        if not src.is_file():
            print(f"MISSING source: {src}", file=sys.stderr)
            return 1
        slug = s["slug"]
        dest_mp4 = OUT_DIR / f"{slug}.mp4"
        dest_jpg = OUT_DIR / f"{slug}.jpg"
        shutil.copy2(src, dest_mp4)
        if not _poster(dest_mp4, dest_jpg):
            print(f"WARN: no poster for {slug} (ffmpeg missing or failed)")
        entry = {
            "id": s["id"],
            "kind": "official",
            "title": s["title"],
            "subtitle": s.get("subtitle"),
            "genre": s.get("genre", "ancient"),
            "style": s.get("style", ""),
            "video_url": f"/samples/{slug}.mp4",
            "cover_url": f"/samples/{slug}.jpg" if dest_jpg.is_file() else None,
            "quality_score": s.get("quality_score"),
            "episodes": s.get("episodes", 1),
            "author_label": author,
            "slug": slug,
        }
        entries.append(entry)
        print(f"OK {src.name} -> {dest_mp4.name} ({dest_mp4.stat().st_size} bytes)")

    catalog_json = OUT_DIR / "catalog.json"
    catalog_json.write_text(
        json.dumps({"author_label": author, "samples": entries}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    ts_lines = [
        "// Auto-generated by scripts/sync_sample_assets.py — do not edit.",
        "import type { GalleryItem } from '@/lib/api';",
        "",
        f"export const OFFICIAL_SAMPLE_AUTHOR = {json.dumps(author, ensure_ascii=False)};",
        "",
        "export const OFFICIAL_SAMPLES: GalleryItem[] = "
        + json.dumps(
            [{k: v for k, v in e.items() if k != "slug"} for e in entries],
            ensure_ascii=False,
            indent=2,
        )
        + ";",
        "",
    ]
    TS_OUT.write_text("\n".join(ts_lines), encoding="utf-8")
    print(f"Wrote {catalog_json} and {TS_OUT}")

    cf_samples = ROOT / "cloudfunctions" / "xyq-api" / "web" / "public" / "samples"
    cf_config = ROOT / "cloudfunctions" / "xyq-api" / "config"
    cf_samples.mkdir(parents=True, exist_ok=True)
    cf_config.mkdir(parents=True, exist_ok=True)
    shutil.copy2(CATALOG, cf_config / "sample_catalog.yaml")
    for f in OUT_DIR.iterdir():
        if f.suffix in {".mp4", ".jpg", ".json"}:
            shutil.copy2(f, cf_samples / f.name)
    print(f"Synced to {cf_samples}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
