apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xyq.fullname" . }}-secrets
  labels:
    app: {{ include "xyq.name" . }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
